import { StyleSheet } from "react-native";
export const C = {
  bg: "#06100b",
  panel: "#0a1711",
  line: "#183025",
  text: "#edf7f1",
  muted: "#70847a",
  green: "#83f8aa",
  blue: "#78a7ff",
  red: "#ff8d82",
};
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  flex: { flex: 1 },
  right: { alignItems: "flex-end", flexShrink: 1 },
  header: {
    position: "relative",
    minHeight: 56,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  logo: { flexShrink: 1, color: C.text, fontWeight: "900", letterSpacing: 2 },
  mainFeatureNav: { flexDirection: "row", gap: 8, paddingHorizontal: 14, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: C.line, backgroundColor: "#07130d" },
  mainFeature: { flex: 1, minHeight: 58, justifyContent: "center", paddingHorizontal: 13, borderWidth: 1, borderColor: C.line, borderRadius: 8, backgroundColor: C.panel },
  mainFeatureActive: { borderColor: C.green, backgroundColor: "#10281b" },
  mainFeatureTitle: { color: C.muted, fontSize: 12, fontWeight: "900" },
  mainFeatureTitleActive: { color: C.green },
  mainFeatureDescription: { marginTop: 4, color: "#587065", fontSize: 8 },
  content: {
    width: "100%",
    maxWidth: 900,
    alignSelf: "center",
    padding: 18,
    paddingBottom: 50,
  },
  landing: {
    width: "100%",
    maxWidth: 640,
    alignSelf: "center",
    flexGrow: 1,
    padding: 24,
    paddingTop: 70,
    paddingBottom: 36,
  },
  eyebrow: {
    color: C.green,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2,
  },
  title: {
    marginTop: 12,
    color: C.text,
    fontSize: 42,
    fontWeight: "900",
    lineHeight: 47,
  },
  subtitle: {
    marginTop: 16,
    marginBottom: 34,
    color: C.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  inputLabel: {
    marginTop: 15,
    marginBottom: 7,
    color: C.muted,
    fontSize: 11,
    fontWeight: "700",
  },
  input: {
    minHeight: 52,
    paddingHorizontal: 15,
    color: C.text,
    fontSize: 16,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 8,
    backgroundColor: C.panel,
  },
  primary: {
    minHeight: 54,
    marginTop: 22,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: C.green,
  },
  disabled: { opacity: 0.75 },
  primaryText: { color: C.bg, fontWeight: "900" },
  loadingRow: { flexDirection: "row", gap: 10, alignItems: "center" },
  progressTrack: {
    height: 4,
    marginTop: 8,
    overflow: "hidden",
    borderRadius: 2,
    backgroundColor: C.line,
  },
  progressFill: { height: 4, backgroundColor: C.green },
  privacy: { marginTop: 18, color: C.muted, fontSize: 10, textAlign: "center" },
  error: { marginTop: 14, color: C.red, textAlign: "center" },
  errorBox: {
    marginTop: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#633",
    borderRadius: 8,
    backgroundColor: "#241310",
  },
  retry: {
    alignSelf: "center",
    marginTop: 10,
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: C.red,
  },
  retryText: { color: C.bg, fontWeight: "900" },
  footer: {
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: 1,
    borderTopColor: C.line,
  },
  homeActions: {
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  favorite: { color: "#ffd76a", fontWeight: "800" },
  searchRow: {
    minHeight: 48,
    flexDirection: "row",
    gap: 16,
    alignItems: "center",
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  profile: {
    flexDirection: "row",
    gap: 15,
    alignItems: "center",
    padding: 18,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 12,
    backgroundColor: C.panel,
  },
  profileName: {
    marginVertical: 4,
    color: C.text,
    fontSize: 22,
    fontWeight: "900",
    flexShrink: 1,
  },
  muted: { color: C.muted, fontSize: 10 },
  centerMuted: {
    marginTop: 12,
    color: C.muted,
    fontSize: 10,
    textAlign: "center",
  },
  green: { color: C.green, fontSize: 10 },
  blue: { color: C.blue, fontSize: 10 },
  heading: {
    marginTop: 28,
    marginBottom: 13,
    color: C.text,
    fontSize: 17,
    fontWeight: "900",
  },
  reportHeading: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between" },
  rangeRow: { flexDirection: "row", gap: 5, marginBottom: 10 },
  rangeChip: { minWidth: 32, paddingVertical: 6, alignItems: "center", borderWidth: 1, borderColor: C.line, borderRadius: 15 },
  rangeChipActive: { backgroundColor: C.green, borderColor: C.green },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  kpi: {
    flexGrow: 1,
    flexBasis: 145,
    minHeight: 105,
    padding: 15,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 8,
    backgroundColor: C.panel,
  },
  label: { color: C.muted, fontSize: 10, fontWeight: "700" },
  kpiValue: {
    marginVertical: 10,
    color: C.text,
    fontSize: 20,
    fontWeight: "900",
  },
  horizontal: { gap: 10 },
  photoWrap: {
    position: "relative",
  },
  photo: {
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: "#11271b",
  },
  playerSeasonIcon: { position: "absolute", left: 0, bottom: 0, zIndex: 4, borderRadius: 2, backgroundColor: "#08110d" },
  photoText: { color: C.green, fontSize: 22, fontWeight: "900" },
  cardPhoto: { position: "relative", alignItems: "center", justifyContent: "center", overflow: "hidden", borderRadius: 10, backgroundColor: "#15251d" },
  cardSeasonIcon: { position: "absolute", left: 0, bottom: 0, zIndex: 3, borderRadius: 2, backgroundColor: "#08110d" },
  dbSearch: { flexDirection: "row", gap: 8, alignItems: "center" },
  dbSearchButton: { minWidth: 68, minHeight: 52, alignItems: "center", justifyContent: "center", borderRadius: 8, backgroundColor: C.green },
  mobileFilterToggle: { minHeight: 46, marginTop: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 15, borderWidth: 1, borderColor: "#315d47", borderRadius: 8, backgroundColor: C.panel },
  mobileFilterToggleActive: { borderColor: C.green, backgroundColor: "#10281b" },
  mobileFilterToggleText: { color: C.text, fontSize: 13, fontWeight: "900" },
  mobileFilterToggleState: { color: C.green, fontSize: 10, fontWeight: "800" },
  mobileFilterPanel: { marginTop: 12, padding: 15, borderWidth: 1, borderColor: "#315d47", borderRadius: 10, backgroundColor: "#08110d" },
  mobileFilterHeading: { flexDirection: "row", gap: 12, alignItems: "flex-start", justifyContent: "space-between", marginBottom: 12 },
  mobileFilterHeadingTitle: { color: C.text, fontSize: 16, lineHeight: 21, fontWeight: "900" },
  mobileFilterDescription: { marginTop: 4, color: C.muted, fontSize: 10, lineHeight: 15 },
  mobileFilterReset: { minHeight: 32, justifyContent: "center", paddingHorizontal: 9, borderWidth: 1, borderColor: C.line, borderRadius: 6, backgroundColor: C.panel },
  mobileFilterResetText: { color: C.green, fontSize: 9, fontWeight: "800" },
  mobileFilterTitle: { marginTop: 17, marginBottom: 9, color: C.text, fontSize: 12, fontWeight: "900" },
  mobileFilterChips: { gap: 6, paddingRight: 8 },
  mobileFilterWrap: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  mobileFilterChip: { minHeight: 34, paddingHorizontal: 11, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: C.line, borderRadius: 6, backgroundColor: C.panel },
  mobileSeasonTitleRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between" },
  mobileSeasonCount: { marginTop: 2, color: C.muted, fontSize: 9 },
  mobileSeasonSearch: { height: 42, marginBottom: 8, paddingHorizontal: 11, color: C.text, borderWidth: 1, borderColor: C.line, borderRadius: 6, backgroundColor: C.bg },
  mobileSeasonGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  mobileSeasonChip: { width: "31.8%", minHeight: 66, padding: 6, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: C.line, borderRadius: 6, backgroundColor: C.panel },
  mobileSeasonImage: { width: 25, height: 25, resizeMode: "contain", marginBottom: 3 },
  mobileSeasonMore: { minHeight: 38, marginTop: 8, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#315d47", borderRadius: 6, backgroundColor: "#0c2016" },
  mobileSeasonEmpty: { paddingVertical: 18, color: C.muted, textAlign: "center", fontSize: 9 },
  mobileFilterChipActive: { borderColor: C.green, backgroundColor: C.green },
  mobileFilterChipText: { color: C.muted, fontSize: 9, lineHeight: 12, fontWeight: "700", textAlign: "center" },
  mobileFilterChipTextActive: { color: C.bg, fontSize: 9, lineHeight: 12, fontWeight: "900", textAlign: "center" },
  mobileFilterPair: { flexDirection: "row", gap: 7, alignItems: "center", marginTop: 8 },
  mobileFilterLabel: { width: 74, color: C.muted, fontSize: 9, fontWeight: "700" },
  mobileFilterInput: { flex: 1, minWidth: 0, height: 40, paddingHorizontal: 9, color: C.text, borderWidth: 1, borderColor: C.line, borderRadius: 5, backgroundColor: C.bg },
  mobileFilterWideInput: { minHeight: 43, marginTop: 9, paddingHorizontal: 10, color: C.text, borderWidth: 1, borderColor: C.line, borderRadius: 5, backgroundColor: C.bg },
  mobileGradeRow: { flexDirection: "row", alignItems: "center", marginTop: 15, gap: 8 },
  mobileStepButton: { width: 34, height: 34, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: C.line, borderRadius: 5, backgroundColor: C.panel },
  mobileGradeValue: { width: 42, color: C.text, textAlign: "center", fontSize: 10, fontWeight: "900" },
  mobileFilterAdd: { minWidth: 48, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 5, backgroundColor: C.green },
  mobileFilterTag: { paddingHorizontal: 9, paddingVertical: 7, borderWidth: 1, borderColor: "#315d47", borderRadius: 5, backgroundColor: "#0c2016" },
  mobileTeamColorRow: { flexDirection: "row", gap: 7, alignItems: "stretch" },
  mobileTeamColorButton: { flex: 1, minWidth: 0, minHeight: 50, flexDirection: "row", gap: 8, alignItems: "center", justifyContent: "space-between", paddingHorizontal: 12, borderWidth: 1, borderColor: C.line, borderRadius: 7, backgroundColor: C.panel },
  mobileTeamColorButtonActive: { borderColor: C.green, backgroundColor: "#10281b" },
  mobileTeamColorText: { flex: 1, color: C.muted, fontSize: 11, fontWeight: "700" },
  mobileTeamColorTextActive: { flex: 1, color: C.text, fontSize: 11, fontWeight: "900" },
  mobileTeamColorLevel: { flexShrink: 0, paddingHorizontal: 7, paddingVertical: 4, color: C.green, fontSize: 9, fontWeight: "900", borderRadius: 10, backgroundColor: "#173b27" },
  mobileTeamColorClear: { minWidth: 54, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#315d47", borderRadius: 7, backgroundColor: "#0c2016" },
  mobileTeamColorClearText: { color: C.green, fontSize: 10, fontWeight: "800" },
  teamColorModalSafe: { flex: 1, backgroundColor: C.bg },
  teamColorModalHeader: { minHeight: 66, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 18, borderBottomWidth: 1, borderBottomColor: C.line },
  teamColorModalClose: { width: 42, height: 42, alignItems: "center", justifyContent: "center" },
  teamColorModalCloseText: { color: C.text, fontSize: 30, lineHeight: 34 },
  teamColorModalSearch: { height: 48, margin: 14, paddingHorizontal: 12, color: C.text, borderWidth: 1, borderColor: "#315d47", borderRadius: 7, backgroundColor: C.panel },
  teamColorModalList: { paddingHorizontal: 14, paddingBottom: 28, gap: 6 },
  teamColorModalItem: { minHeight: 49, flexDirection: "row", gap: 10, alignItems: "center", justifyContent: "space-between", paddingHorizontal: 12, paddingVertical: 9, borderWidth: 1, borderColor: C.line, borderRadius: 6, backgroundColor: C.panel },
  teamColorModalItemActive: { borderColor: C.green, backgroundColor: C.green },
  teamColorModalItemText: { flex: 1, color: C.text, fontSize: 10, fontWeight: "700" },
  teamColorModalItemTextActive: { flex: 1, color: C.bg, fontSize: 10, fontWeight: "900" },
  teamColorModalItemLevel: { flexShrink: 0, color: C.muted, fontSize: 8 },
  teamColorModalItemLevelActive: { flexShrink: 0, color: C.bg, fontSize: 8, fontWeight: "900" },
  teamColorModalHint: { paddingVertical: 14, color: C.muted, textAlign: "center", fontSize: 8 },
  dbList: { marginTop: 18 },
  dbRow: { minHeight: 94, flexDirection: "row", gap: 10, alignItems: "center", paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: C.line },
  dbResultNameRow: { flexDirection: "row", gap: 6, alignItems: "center" },
  dbResultPlayerName: { flex: 1 },
  dbFeet: { flexShrink: 0, flexDirection: "row", gap: 3, alignItems: "center" },
  dbFootBadge: { flexDirection: "row", gap: 2, alignItems: "center", paddingHorizontal: 4, paddingVertical: 3, borderRadius: 9, backgroundColor: "#143a25" },
  dbFootLabel: { color: "#a8b8af", fontSize: 6, fontWeight: "700" },
  dbFootValue: { color: C.green, fontSize: 8, fontWeight: "900" },
  dbCompactMeta: { flexDirection: "row", gap: 7, alignItems: "center", marginTop: 8 },
  dbPosition: { color: C.green, fontSize: 10, fontWeight: "900" },
  dbSalary: { color: "#97aaa0", fontSize: 8 },
  dbGradeBadge: { paddingHorizontal: 6, paddingVertical: 4, color: C.text, fontSize: 8, fontWeight: "900", borderRadius: 4, backgroundColor: "#33413a" },
  dbResultActions: { width: 42, gap: 8, alignItems: "center" },
  compareChoice: { minWidth: 38, minHeight: 25, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: C.line, borderRadius: 5, backgroundColor: C.panel },
  compareChoiceActive: { borderColor: C.green, backgroundColor: C.green },
  compareChoiceText: { color: C.muted, fontSize: 7, fontWeight: "800" },
  compareChoiceTextActive: { color: C.bg, fontSize: 7, fontWeight: "900" },
  compareHint: { marginTop: 14, padding: 12, color: C.green, fontSize: 9, borderWidth: 1, borderColor: "#315d47", borderRadius: 7, backgroundColor: "#0c2016" },
  comparePanel: { marginTop: 16, padding: 14, borderWidth: 1, borderColor: "#315d47", borderRadius: 9, backgroundColor: "#0a1911" },
  compareHeading: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" },
  compareClose: { color: C.text, fontSize: 28, lineHeight: 31 },
  compareHeroes: { flexDirection: "row", gap: 8, marginVertical: 14 },
  compareHero: { flex: 1, minWidth: 0, alignItems: "center", gap: 4, padding: 10, borderWidth: 1, borderColor: C.line, borderRadius: 8, backgroundColor: C.panel },
  compareGrade: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 7 },
  compareGradeButton: { width: 26, height: 26, color: C.green, textAlign: "center", textAlignVertical: "center", fontSize: 16, borderWidth: 1, borderColor: C.line, borderRadius: 4 },
  compareGradeValue: { minWidth: 30, color: C.text, textAlign: "center", fontSize: 9, fontWeight: "900" },
  compareTable: { marginTop: 6, borderTopWidth: 1, borderTopColor: C.line },
  compareOverall: { minHeight: 58, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: C.line },
  compareOverallValue: { flex: 1, textAlign: "center", fontSize: 28, fontWeight: "900" },
  compareLabel: { width: 90, color: C.muted, textAlign: "center", fontSize: 9, fontWeight: "700" },
  compareRow: { minHeight: 43, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: C.line },
  compareStat: { flex: 1, flexDirection: "row", justifyContent: "center", gap: 5, alignItems: "baseline" },
  compareStatValue: { color: C.text, fontSize: 13, fontWeight: "900" },
  compareWinner: { color: C.green },
  compareDelta: { color: C.muted, fontSize: 7 },
  dbOvr: { flexShrink: 0, paddingHorizontal: 6, paddingVertical: 4, color: C.bg, fontSize: 8, fontWeight: "900", borderRadius: 4, backgroundColor: C.green },
  dbMeta: { marginTop: 4, color: "#97aaa0", fontSize: 8 },
  dbHero: { flexDirection: "row", gap: 16, alignItems: "center", paddingVertical: 20 },
  dbNotice: { marginTop: 24, padding: 14, color: C.muted, fontSize: 10, lineHeight: 17, borderWidth: 1, borderColor: C.line, borderRadius: 8 },
  dbOverall: { marginTop: 8, color: C.green, fontSize: 20, fontWeight: "900" },
  dbOverallRow: { flexDirection: "row", gap: 7, alignItems: "baseline" },
  dbValueRow: { flexDirection: "row", gap: 5, alignItems: "baseline", justifyContent: "center" },
  dbDelta: { color: "#25d66f", fontSize: 10, fontWeight: "900" },
  dbGradeRow: { gap: 5, alignItems: "center", paddingBottom: 18 },
  dbGradeLabel: { marginRight: 8, color: C.text, fontSize: 10, fontWeight: "800" },
  dbGrade: { width: 38, height: 32, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: C.line, borderRadius: 5, backgroundColor: C.panel },
  dbGradeActive: { borderColor: C.green, backgroundColor: C.green },
  dbGradeActiveText: { color: C.bg, fontSize: 10, fontWeight: "900" },
  dbPills: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginVertical: 10 },
  dbPill: { paddingHorizontal: 10, paddingVertical: 7, color: C.muted, fontSize: 9, borderWidth: 1, borderColor: C.line, borderRadius: 18, backgroundColor: C.panel },
  dbTeamColor: { marginBottom: 14, padding: 14, gap: 8, borderWidth: 1, borderColor: "#315d47", borderRadius: 9, backgroundColor: "#0c2016" },
  headingCompact: { color: C.text, fontSize: 17, lineHeight: 22, fontWeight: "900" },
  dbSelectorGroup: { gap: 6, marginTop: 5 },
  dbSelectorLabel: { color: C.text, fontSize: 10, fontWeight: "800" },
  dbSelectorRow: { flexDirection: "row", gap: 6, alignItems: "center", paddingRight: 8 },
  dbChoice: { minHeight: 34, justifyContent: "center", paddingHorizontal: 11, borderWidth: 1, borderColor: C.line, borderRadius: 18, backgroundColor: C.panel },
  dbChoiceActive: { borderColor: C.green, backgroundColor: C.green },
  dbChoiceActiveText: { color: C.bg, fontSize: 9, fontWeight: "900" },
  dbSummary: { flexDirection: "row", flexWrap: "wrap", marginTop: 8, borderWidth: 1, borderColor: C.line },
  dbSummaryCell: { width: "33.333%", minHeight: 70, alignItems: "center", justifyContent: "center", borderWidth: 0.5, borderColor: C.line, backgroundColor: C.panel },
  dbAbilityValue: { marginTop: 5, color: C.green, fontSize: 18, fontWeight: "900" },
  dbPanel: { padding: 15, borderWidth: 1, borderColor: C.line, borderRadius: 8, backgroundColor: C.panel },
  dbPrice: { marginBottom: 12, color: C.text, fontSize: 22, fontWeight: "900" },
  dbPriceBars: { height: 80, flexDirection: "row", gap: 2, alignItems: "flex-end" },
  dbPriceBar: { flex: 1, minWidth: 2, backgroundColor: C.green, borderTopLeftRadius: 2, borderTopRightRadius: 2 },
  dbPriceDates: { marginTop: 5, flexDirection: "row", justifyContent: "space-between" },
  dbStatGrid: { flexDirection: "row", flexWrap: "wrap", gap: 5 },
  dbStat: { width: "23.5%", minHeight: 64, alignItems: "center", justifyContent: "center", padding: 7, borderWidth: 1, borderColor: C.line, borderRadius: 5, backgroundColor: C.panel },
  dbAbilityGrid: { flexDirection: "row", alignItems: "flex-start", gap: 5 },
  dbAbility: { minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 8, borderWidth: 1, borderColor: C.line, borderRadius: 5, backgroundColor: C.panel },
  dbAbilityBoosted: { borderColor: "#315d4755", backgroundColor: "#0a1510" },
  dbTrainingHeading: { flexDirection: "row", gap: 8, alignItems: "center", marginTop: 22, marginBottom: 10 },
  dbTrainingCount: { color: C.green, fontSize: 11, fontWeight: "900" },
  dbTrainingActions: { gap: 5 },
  dbTrainingReset: { paddingHorizontal: 8, paddingVertical: 6, borderWidth: 1, borderColor: C.line, borderRadius: 5, backgroundColor: C.panel },
  dbTrainingResetText: { color: C.text, fontSize: 8, fontWeight: "800" },
  dbTrainingValue: { alignItems: "flex-end", gap: 5 },
  dbTrainingControls: { flexDirection: "row", alignItems: "center", gap: 4 },
  dbTrainingButton: { width: 24, height: 24, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: C.line, borderRadius: 5, backgroundColor: C.bg },
  dbTrainingButtonText: { color: C.green, fontSize: 13, fontWeight: "900" },
  dbTrainingLevel: { minWidth: 10, color: C.text, textAlign: "center", fontSize: 8, fontWeight: "900" },
  dbTrainingDisabled: { opacity: 0.35 },
  dbEffectFilter: { gap: 6, alignItems: "center", paddingBottom: 10, paddingRight: 8 },
  dbEffectChip: { minHeight: 32, justifyContent: "center", paddingHorizontal: 10, borderWidth: 1, borderColor: C.line, borderRadius: 16, backgroundColor: C.panel },
  dbEffectChipActive: { borderColor: C.green, backgroundColor: C.green },
  dbPurple: { color: "#9a78ff", fontSize: 17, fontWeight: "900" },
  dbClub: { minHeight: 50, flexDirection: "row", gap: 10, alignItems: "center", borderBottomWidth: 1, borderBottomColor: C.line },
  dbClubHeader: { minHeight: 34, borderBottomColor: "#315d47" },
  dbClubYears: { width: 90, color: C.muted, fontSize: 9 },
  dbClubName: { flex: 1, color: C.text, fontSize: 11, lineHeight: 16, fontWeight: "800" },
  dbClubLoan: { width: 38, color: C.muted, fontSize: 9, textAlign: "right" },
  playerCard: {
    width: 126,
    padding: 12,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 9,
    backgroundColor: C.panel,
  },
  playerName: {
    marginVertical: 4,
    color: C.text,
    fontSize: 12,
    fontWeight: "800",
    flexShrink: 1,
  },
  playerRow: {
    minHeight: 72,
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  matchRow: {
    minHeight: 72,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  matchNo: { width: 22, color: C.muted, fontSize: 10 },
  result: {
    width: 44,
    height: 29,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 5,
  },
  score: { color: C.text, fontSize: 18, fontWeight: "900" },
  arrow: { color: C.muted, fontSize: 17 },
  warning: {
    marginTop: 12,
    padding: 12,
    color: "#d8b679",
    backgroundColor: "#2a2112",
    borderRadius: 6,
  },
  back: { position: "absolute", zIndex: 5, left: 14, top: 7, minHeight: 42, justifyContent: "center", paddingHorizontal: 6 },
  backText: { color: C.green, fontWeight: "800" },
  scoreHero: {
    minHeight: 150,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  shareCard: { backgroundColor: C.bg, paddingHorizontal: 8 },
  shareCredit: { paddingBottom: 8, color: C.muted, fontSize: 8, textAlign: "center" },
  shareButton: { alignSelf: "center", marginBottom: 12, paddingHorizontal: 16, paddingVertical: 9, borderWidth: 1, borderColor: C.line, borderRadius: 18 },
  shareButtonText: { color: C.green, fontSize: 10, fontWeight: "800" },
  club: { width: "28%", alignItems: "center" },
  clubName: {
    color: C.text,
    fontSize: 14,
    fontWeight: "900",
    textAlign: "center",
  },
  heroScore: { color: C.text, fontSize: 36, fontWeight: "900" },
  tabs: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  tab: { flex: 1, paddingVertical: 13, alignItems: "center" },
  activeTab: { borderBottomWidth: 2, borderBottomColor: C.green },
  goalRow: {
    minHeight: 58,
    flexDirection: "row",
    gap: 15,
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  minute: { width: 42, fontSize: 17, fontWeight: "900" },
  rating: { color: C.green, fontSize: 17, fontWeight: "900" },
  stats: { marginTop: 18 },
  stat: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  statValue: {
    width: 70,
    color: C.text,
    fontSize: 15,
    fontWeight: "900",
    textAlign: "center",
  },
  sideTabs: {
    marginVertical: 18,
    flexDirection: "row",
    justifyContent: "space-around",
  },
  pitch: {
    position: "relative",
    height: 500,
    marginTop: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#ffffff35",
    borderRadius: 8,
    backgroundColor: "#0d281b",
  },
  formationPitch: {
    position: "relative",
    height: 620,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#ffffff35",
    borderRadius: 8,
    backgroundColor: "#0d281b",
  },
  formationTitle: { marginVertical: 10, color: C.text, textAlign: "center", fontWeight: "800" },
  liveScore: { color: C.text, fontWeight: "900", fontVariant: ["tabular-nums"] },
  bestCompare: { gap: 8 },
  filterChip: { paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1, borderColor: C.line, borderRadius: 18 },
  filterChipActive: { backgroundColor: C.green, borderColor: C.green },
  filterTextActive: { color: C.bg, fontSize: 10, fontWeight: "900" },
  halfway: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "50%",
    borderTopWidth: 1,
    borderTopColor: "#ffffff30",
  },
  centerCircle: {
    position: "absolute",
    left: "35%",
    top: "41%",
    width: "30%",
    aspectRatio: 1,
    borderWidth: 1,
    borderColor: "#ffffff30",
    borderRadius: 999,
  },
  centerSpot: {
    position: "absolute",
    left: "49.3%",
    top: "49.3%",
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#ffffff40",
  },
  topPenalty: {
    position: "absolute",
    left: "25%",
    top: -1,
    width: "50%",
    height: "16%",
    borderWidth: 1,
    borderColor: "#ffffff30",
  },
  topGoalArea: {
    position: "absolute",
    left: "38%",
    top: -1,
    width: "24%",
    height: "6%",
    borderWidth: 1,
    borderColor: "#ffffff30",
  },
  bottomPenalty: {
    position: "absolute",
    left: "25%",
    bottom: -1,
    width: "50%",
    height: "16%",
    borderWidth: 1,
    borderColor: "#ffffff30",
  },
  bottomGoalArea: {
    position: "absolute",
    left: "38%",
    bottom: -1,
    width: "24%",
    height: "6%",
    borderWidth: 1,
    borderColor: "#ffffff30",
  },
  shotLegend: {
    marginTop: 18,
    flexDirection: "row",
    justifyContent: "center",
    gap: 20,
    flexWrap: "wrap",
  },
  shot: {
    position: "absolute",
    zIndex: 4,
    width: 12,
    height: 12,
    marginLeft: -6,
    marginTop: -6,
    borderWidth: 2,
    borderColor: C.green,
    borderRadius: 7,
    backgroundColor: "#0d281b",
  },
  goalShot: {
    width: 15,
    height: 15,
    marginLeft: -7.5,
    marginTop: -7.5,
    borderColor: C.text,
    backgroundColor: C.text,
  },
  shotDetail: {
    marginTop: 10,
    minHeight: 66,
    padding: 12,
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 8,
    backgroundColor: C.panel,
  },
  shotBadge: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 21,
  },
  shotBadgeText: { color: C.bg, fontWeight: "900" },
  formationPlayer: {
    position: "absolute",
    zIndex: 4,
    width: 78,
    marginLeft: -39,
    marginTop: -30,
    alignItems: "center",
  },
  formationRating: {
    position: "absolute",
    right: -7,
    top: -4,
    paddingHorizontal: 5,
    paddingVertical: 2,
    overflow: "hidden",
    color: C.bg,
    fontSize: 8,
    fontWeight: "900",
    borderRadius: 8,
    backgroundColor: C.green,
  },
  formationName: {
    width: 78,
    marginTop: 3,
    color: C.text,
    fontSize: 9,
    fontWeight: "800",
    textAlign: "center",
  },
  formationMeta: { color: C.muted, fontSize: 7, textAlign: "center" },
  playerEvents: {
    position: "absolute",
    left: 29,
    bottom: -4,
    flexDirection: "row",
  },
  eventIcon: { marginLeft: -3, fontSize: 9 },
  playerHero: {
    flexDirection: "row",
    gap: 15,
    alignItems: "center",
    paddingVertical: 24,
  },
  playerHeroName: {
    marginVertical: 7,
    color: C.text,
    fontSize: 22,
    fontWeight: "900",
    flexShrink: 1,
  },
  heroRating: { color: C.green, fontSize: 24, fontWeight: "900" },
  bars: {
    height: 190,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 6,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  barWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 5,
  },
  bar: {
    width: "70%",
    maxWidth: 26,
    backgroundColor: C.green,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  mobileFilterApply: { minHeight: 45, marginTop: 18, alignItems: "center", justifyContent: "center", borderRadius: 6, backgroundColor: C.green },
  dbResultsHeading: { marginTop: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  dbResultsEdit: { minHeight: 34, paddingHorizontal: 11, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#315d47", borderRadius: 6, backgroundColor: "#0c2016" },
  dbEstimate: { color: C.muted, fontSize: 7, fontWeight: "800" },
  dbEstimateNote: { marginTop: 3, color: C.muted, fontSize: 7 },
  dbAbilityColumn: { flex: 1, minWidth: 0, gap: 5 },
  dbAbilityTrained: { borderColor: "#5caa7b", backgroundColor: "#0a1710" },
});
